name: DebugBuild
on:
  push:
    branches:
      - '**' 

env:
  SOLUTION_FILE_PATH: YoRigine.sln
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 最新のv4を使用
        with:
          submodules: recursive # 【重要】ライブラリのソースコードを全部持ってくる

      - name: Setup Visual Studio with C++ v145
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17'

      - name: Run Premake to Generate Solution
        shell: cmd # 明示的にコマンドプロンプトで実行
        run: |
          .\premake.bat

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Debug Build
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64,Configuration=${{ env.CONFIGURATION }}
